version: '3.8'

services:
  nuanced-news:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    depends_on:
      - rss-parser
    command: ["make", "run"]

  rss-parser:
    build: .
    command: ["python", "rss_parser.py"]
    volumes:
      - ./backend:/app/backend